//IIFE
//WE USE IIFE TO PREVENT THE GLOABL SCOPE POLLUTION WHICH MUST NOT INCLUDE IN A FUNCTION AT ANY COST
//IIFE - IMMEDIATELY INVOKED FUNCTION  EXPRESSIONS

//  NORMAL CALLING
function myFun(){
    console.log("this is IIFE EXAMPLE")
}
myFun();

//IMMEDIATE CALLING USING IIFE
//WE USE ()()
//WE ENCLOSE OUR FUNCTION IN A PARANTHESIS

(function myFun2(){
    console.log("this is IIFE2 EXAMPLE")
})();

//IF WE WANT TO DECALRE 2 0R MORE WITH IIFE WE SHOULD USE SEMI COLON AT END OF EVERY FUNCTION
//ALSSO CALLED AS THE BELOW SIMPLE IIFE
( () =>{
    console.log("this is an iife function using arrow function")
} )()